services:
  db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: recipe_box_production

  api:
    build:
      context: ./recipe_box_api
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/recipe_box_production
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: true
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY:-}
      DB_HOST: db
      DB_USERNAME: postgres
      DB_PASSWORD: password
    ports:
      - "3000:3000"
    volumes:
      - ./recipe_box_api/config/master.key:/app/config/master.key

  client:
    build:
      context: ./recipe_box_client
    restart: always
    depends_on:
      - api
    ports:
      - "8080:80"

volumes:
  postgres_data:
